force-app/main/default/objects/SupportRequest__c/SupportRequest__c.object-meta.xml
<CustomObject>
    <description>Objecto que guarda los datos de las solicitudes de soporte.</description>
    <label>Solicitud soporte</label>
    <nameField>
        <displayFormat>SR{YYYYMMDD}-{0}</displayFormat>
        <label>Identificador solicitud</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Solicitudes soporte</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SupportRequest__c/fields/ExpectedResolutionDate__c.field-meta.xml
<CustomField>
    <fullName>ExpectedResolutionDate__c</fullName>
    <description>Fecha de resolución esperada de la solicitud.</description>
    <label>Fecha de resolución esperada</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SupportRequest__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <description>Prioridad de la solicitud</description>
    <label>Prioridad</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
                <label>Alta</label>
            </value>
            <value>
                <fullName>Medium</fullName>
                <label>Media</label>
            </value>
            <value>
                <fullName>Low</fullName>
                <label>Baja</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SupportRequest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Estado de la solicitud.</description>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ToManage</fullName>
                <label>Por gestionar</label>
            </value>
            <value>
                <fullName>InProcess</fullName>
                <label>En proceso</label>
            </value>
            <value>
                <fullName>PendingInternal</fullName>
                <label>Pendiente interno</label>
            </value>
            <value>
                <fullName>PendingCustomer</fullName>
                <label>Pendiente cliente</label>
            </value>
            <value>
                <fullName>Closed</fullName>
                <label>Cerrado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UpdateSupportRequestByStatusBatch.cls
global class UpdateSupportRequestByStatusBatch
    implements Database.Batchable<SObject>, Schedulable {

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([
            SELECT Id, Priority__c,ExpectedResolutionDate__c
            FROM SupportRequest__c where Status__c='PendingInternal' OR Status__c='PendingCustomer'
        ]);
    }

    global void execute(Database.BatchableContext bc, List<SupportRequest__c> scope) {
        List<SupportRequest__c> updates = new List<SupportRequest__c>(scope.size());
        system.debug('entra execute' + scope);
        for (SupportRequest__c sr : scope) {
            Integer dias;
            if (sr.Priority__c == 'High') {
                dias = 1;
            } else if (sr.Priority__c == 'Medium') {
                dias = 3;
            } else if(sr.Priority__c=='Low'){
                dias = 5;
            }
            if(sr.ExpectedResolutionDate__c!=null && dias!=null){
                sr.ExpectedResolutionDate__c = DiasHabilesCheck.sumarDiasHabiles(Date.today(), dias);
            }
        }

        update scope;


    }

    global void finish(Database.BatchableContext bc) {
        System.debug('Batch de actualización de solicitudes completado.');

    }

    global void execute(SchedulableContext sc) {
        Database.executeBatch(this, 200);
    }
}