force-app/main/default/objects/SupportRequest__c/SupportRequest__c.object-meta.xml
<CustomObject>
    <description>Objecto que guarda los datos de las solicitudes de soporte.</description>
    <label>Solicitud soporte</label>
    <nameField>
        <displayFormat>SR{YYYYMMDD}-{0}</displayFormat>
        <label>Identificador solicitud</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Solicitudes soporte</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SupportRequest__c/fields/ExpectedResolutionDate__c.field-meta.xml
<CustomField>
    <fullName>ExpectedResolutionDate__c</fullName>
    <description>Fecha de resolución esperada de la solicitud.</description>
    <label>Fecha de resolución esperada</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SupportRequest__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <description>Prioridad de la solicitud</description>
    <label>Prioridad</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
                <label>Alta</label>
            </value>
            <value>
                <fullName>Medium</fullName>
                <label>Media</label>
            </value>
            <value>
                <fullName>Low</fullName>
                <label>Baja</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/botonSupportController.cls
public with sharing class botonSupportController {
    
    @AuraEnabled
    public static void actualizarFecha(Id recordId) {
        system.debug('llega');
        SupportRequest__c sr = [
            SELECT Id, Priority__c,ExpectedResolutionDate__c
            FROM SupportRequest__c
            WHERE Id = :recordId
            LIMIT 1
        ];
        Integer dias = getDiasPorPrioridad(sr.Priority__c);
        if(sr.ExpectedResolutionDate__c!=null && dias!=null){
            sr.ExpectedResolutionDate__c = botonSupportController.sumarDiasHabiles(Date.today(), dias);

        }        
        update sr;
    }
    
    
    
    
    
    private static Integer getDiasPorPrioridad(String prioridad) {
        if (prioridad == 'High'){
            return 1;
        }   
        if (prioridad == 'Medium'){
            return 3;
        } 
        if (prioridad=='Low'){
            return 5;
            } 
        return null;
    }

    private static Date sumarDiasHabiles(Date fechaInicio, Integer dias) {
       
        if (fechaInicio == null || dias == null || dias <= 0) {
            return fechaInicio;
        }
        

        Date d = fechaInicio;
        Integer added = 0;

        while (added < dias) {
            d = d.addDays(1);
            Integer dow = d.toStartOfWeek().daysBetween(d);
            if (dow != 0 && dow != 6) { 
                added++;
            }
        }
        return d;
    }
}